// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppFasitec.Context;

namespace WebAppFasitec.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210403124305_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAppFasitec.Entities.Contrato", b =>
                {
                    b.Property<int>("IdContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Datacadastro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPessoa")
                        .HasColumnType("int");

                    b.Property<int>("NumeroContrato")
                        .HasColumnType("int");

                    b.Property<int?>("PessoasIdPessoa")
                        .HasColumnType("int");

                    b.Property<int>("QtdeParcelas")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdContrato");

                    b.HasIndex("PessoasIdPessoa");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("WebAppFasitec.Entities.Fatura", b =>
                {
                    b.Property<int>("IdFatura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataFechamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPessoa")
                        .HasColumnType("int");

                    b.Property<bool>("Pago")
                        .HasColumnType("bit");

                    b.Property<int?>("PessoasIdPessoa")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdFatura");

                    b.HasIndex("PessoasIdPessoa");

                    b.ToTable("Faturas");
                });

            modelBuilder.Entity("WebAppFasitec.Entities.Parcela", b =>
                {
                    b.Property<int>("IdParcela")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ContratoIdContrato")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FaturaIdFatura")
                        .HasColumnType("int");

                    b.Property<int>("IdContrato")
                        .HasColumnType("int");

                    b.Property<int?>("IdFatura")
                        .HasColumnType("int");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdParcela");

                    b.HasIndex("ContratoIdContrato");

                    b.HasIndex("FaturaIdFatura");

                    b.ToTable("Parcelas");
                });

            modelBuilder.Entity("WebAppFasitec.Entities.Pessoa", b =>
                {
                    b.Property<int>("IdPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiaCobranca")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdPessoa");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("WebAppFasitec.Entities.Contrato", b =>
                {
                    b.HasOne("WebAppFasitec.Entities.Pessoa", "Pessoas")
                        .WithMany("Contratos")
                        .HasForeignKey("PessoasIdPessoa");

                    b.Navigation("Pessoas");
                });

            modelBuilder.Entity("WebAppFasitec.Entities.Fatura", b =>
                {
                    b.HasOne("WebAppFasitec.Entities.Pessoa", "Pessoas")
                        .WithMany("Faturas")
                        .HasForeignKey("PessoasIdPessoa");

                    b.Navigation("Pessoas");
                });

            modelBuilder.Entity("WebAppFasitec.Entities.Parcela", b =>
                {
                    b.HasOne("WebAppFasitec.Entities.Contrato", "Contrato")
                        .WithMany("Parcelas")
                        .HasForeignKey("ContratoIdContrato");

                    b.HasOne("WebAppFasitec.Entities.Fatura", "Fatura")
                        .WithMany("Parcelas")
                        .HasForeignKey("FaturaIdFatura");

                    b.Navigation("Contrato");

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("WebAppFasitec.Entities.Contrato", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("WebAppFasitec.Entities.Fatura", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("WebAppFasitec.Entities.Pessoa", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("Faturas");
                });
#pragma warning restore 612, 618
        }
    }
}
